### ISSUE TITLE
Geckos 

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#152]
Ambient mobs, I suppose. Docile, spawn in Coarse Islands, drop nothing. They run and hide inside bush blocks when the player gets near. I'll get some custom sounds done.

**Comment by PCAwesomeness** [comment]
How finished are they?

**Comment by MrCompost** [comment]
They still need their AI doing. I could fill in some bits but not the "they run and hide inside bush blocks when the player gets near" bit.

**Comment by BobMowzie** [comment]
I can make them run away easily. Not sure about the hiding. How exactly do you want that to work?

**Comment by MrCompost** [comment]
Basically it goes inside the nearest bush block.

**Comment by BobMowzie** [comment]
And stands there? Or disappears?

**Comment by MrCompost** [comment]
I hadn't really thought of that. Perhaps it should disappear. Would make hunting them a challenge if we ever have them drop anything.
