### ISSUE TITLE
Models for Len or Rik to do

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#156]
*Purple Pear crop
*Yellow Dotted Fungus crop
*Those cave things you mentioned
*Er... anything else I guess, the crops are probably the most important atm.

**Comment by TripleHeadedSheep** [comment]
"*Er... anything else I guess,"

You're always so clear when it comes to this stuff.... x)

**Comment by MrCompost** [comment]
BAH, whatever!

**Comment by MrCompost** [comment]
May as well just close this.
