### ISSUE TITLE
Spirit Tree

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#159]
The tree is made up of Spirit Tree Logs, a Spirit Tree Face and Spirit Tree Leaves. Spirit Tree logs work as you would expect, though I need to do the top texture. The leaves are sort of like vines, but are 3 blocks tall and use three separate textures. They drop Spirit Tree Saplings, and sometimes Spirit Fruit, as a vanilla tree would drop apples on occasion. Spirit Fruits are basically just like golden apples, though not the enchanted variety. 
The way the Spirit Tree Face works is as followed - 
The block looks like a spirit tree log, expect on one side there is a face.
Normally, the tree uses it's sleeping texture, but when you get within a 10 block radius, it will open its eyes with the awakened texture. When you get within 5 blocks, the face will change to enraged. At this point it will attack by firing blue projectiles... or spitting at you. It makes a custom sound and the face changed to the attack texture every time it does it. It takes quite a long time to break, but I don't think as long as something like obsidian. It just drops a regular spirit tree log when broken.

**Comment by TripleHeadedSheep** [comment]
Ok, the face wont be a texture but a model ;)

**Comment by MrCompost** [comment]
This doesn't need to be open atm
