### ISSUE TITLE
A bunch of blocks

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#160]
May as well list them all together here.
*Fence gates for all the types of wood we have. - DONE
*Silt Glass/Silt Glass Panes - DONE
*Thatch Roofing - DONE
*Weedwood Jukebox (acts like like a regular jukebox) - DONE
*Weedwood Ladder - DONE
*Weedwood Trapdoor - DONE
*Octine Trapdoor (opened by buttons, levers, pressure plates etc.) - DONE
*Octine Door (opened by buttons, levers, pressure plates etc.) - DONE
*Totem Block (acts like Netherack) - DONE
*Weedwood Pressure Plate - DONE
*Betweenstone Pressure Plate - DONE
*Octine Pressure Plate - DONE
*Weedwood Button - DONE
*Betweenstone Button - DONE
*Weedwood Lever - DONE
*Mud Flower Pot DONE
*Thatch slabs DONE
*Weedwood Item Frame REMOVED
*Weedwood Sign

**Comment by TripleHeadedSheep** [comment]
I'll make models for:
Weedwood Jukebox
Weedwood Ladder
(Maybe) Weedwood Trapdoor
(Maybe) Octine Trapdoor
Mud Flower Pot

**Comment by TripleHeadedSheep** [comment]
Weedwood frames are replaced by shelves btw

**Comment by MrCompost** [comment]
kk

**Comment by imdutch21** [comment]
signs are added, so unless you still want the item frames this issue can be closed

**Comment by TheCyberBrick** [comment]
Uhm, the signs don't render :P

**Comment by MrCompost** [comment]
Heh, that's probably an issue :P
As for the item frames, I personally would like them, but if nobody else cares for them then don't bother.

**Comment by imdutch21** [comment]
@TheCyberBrick Weird because they work for me, it could be my git did not commit changes that invole capitalization

**Comment by TripleHeadedSheep** [comment]
For the item frames, I guess that's why we have shelves now...
I dont really care for them tbh. Close the issue?

**Comment by MrCompost** [comment]
Hmmm they work for me too Bart. 

Alright then, I'll just close the issue.
