### ISSUE TITLE
Model rendering issue 

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#166]
For whatever reason, sometimes the textures on the blocks with models get messed up. It happens to the Mud Brick Flower Pot a lot.

**Comment by TheCyberBrick** [comment]
I have yet to see this bug and I am not sure what could be causing it

**Comment by imdutch21** [comment]
I don't think we should have this as a issue untill someone has a screenshot of it happening again(as the flower pot was a derp from the texture). Just make sure that everyone that has acces to the mod knows that they should make a screenshot if this happens.

**Comment by TheCyberBrick** [comment]
I have seen pictures of this. Paul thinks it's due to texture restitching while the game is already running, though we're not exactly sure why or what would cause that.

**Comment by MrCompost** [comment]
Several of us have seen this on more than one occasion Bart, me included.

**Comment by TripleHeadedSheep** [comment]
Another issue in this regard. The Pestle and Mortar block model isnt correct, it has some missing parts. atleast for me.
The missing parts are two wood details, there are 4 in total and 2 of them dont render, the other one is the dried herb hanging from the side.

**Comment by TheCyberBrick** [comment]
The P&M is a TESR, doesn't have to do anything with my model renderer ;)
