### ISSUE TITLE
Compost Bin

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#170]
No GUI needed here. Simply right click with a compostable item (if an item can't be used, a message is displayed in that chat saying "You cannot compost this item.", leave it for 10 minutes and it will be compost. If it is at 100% it will say "The Compost Bin is full.". You right click it with an empty hand to obtain the Compost item. One compost uses 25%. If there is less than 25% a message will say "There is not enough compost yet." The items you throw in are rendered piled up like with the animator and purifier. The amount of compost is also rendered, and the more stuff you add the more it fills up. Any items you throw in are rendered on top of the existing pile of compost if there already is some. 
Different items fill different amounts. Common materials such as bark only fill 1%, sticks 2% or something and so on. You can make this bit up really, though moss should be 10% and rotten bark should be 25%, which is a lot more than anything else. This is a lot more complicated than I had imagined.

**Comment by TripleHeadedSheep** [comment]
Closing this, seems pretty much done
