### ISSUE TITLE
Middle Gem Circle

### ISSUE THREAD

**Issue by TripleHeadedSheep** [Angry-Pixel/The-Betweenlands#172]
There will be some sort of circle for the middle gems for when they're used in combat (like rock, paper, scissors):

Green beats aqua,
Aqua beats crimson,
Crimson beats green.

This allows for more interesting combat.
The gems can be applies to weaponry or armour (so for swords or for amulets/pendants for the player to wear).

-> The crimson sword does extra damage to green amulets, normal against nothing or crimson, and less damage against aqua amulets
-> The green one does extra against aqua, normal against nothing or green, and less against crimson
-> Aqua does extra to crimson, normal to nothing or aqua, and less against green.

This system is not only good for better PvP, but will also be applied to some mobs (See the issue on Temple Guardians)

**Comment by TheCyberBrick** [comment]
Tools/Armor can be combined with the gems in a normal crafting table or inventory.
If the tool/armor already has a gem on it, it can either be removed by combining it with the opposite gem or it can be replaced by using the gem that is neutral to it

**Comment by TheCyberBrick** [comment]
The damage is changed depending on the gem of the attacker item and the gem of the attacker entity (e.g. for the temple guardians which have a gem applied by default, or we could also make entities sometimes spawn with a gem applied) in relation to the gem of the attacked entity armor, attacked entity (again, for entites like the temple guardian) and the blocking item (e.g. a blocking sword)

**Comment by TheCyberBrick** [comment]
Actually, there should be some sort of indication of what gems the entity is using. Easiest solution would be to render some sort of shield, perhaps similar to the repeller shield, but not as strong and very faint. The shield would have the gem's color (or a mixture between the color of multiple gems if the entity has different gems, e.g. on tools and armor) and the more gems the stronger the shield renders. Imo that would look pretty cool.
If you have any other suggestions just comment them here.

**Comment by TheCyberBrick** [comment]
As it stands right now, the middle gem circle is quite pointless because you can just have three swords with each of the gems and then use what's most effective against the opponent. There should be more to those gems, for example:
- Crimson has a small chance to set the opponent on fire
- Green has a small chance to heal the user by a percentage of the damage dealt
- Aqua has a small chance for a short defense buff (some seconds) when attacked
The chances for these things should be rather small but still enough that it actually matters which gems you're using. Like that it's not just only like rock, paper, scissors but it also gives the user an actual advantage over other players that don't have any gem at all.

**Comment by TripleHeadedSheep** [comment]
Seems a good idea, this also goes for enemies I assume?

**Comment by MrCompost** [comment]
Oh hey, you're back =)
Sorry I haven't been about myself these past few days, been really busy. I was thinking that myself actually, but to be honest I don't really like that solution either. They seem too... random I suppose, and also more like enchantments of swords. Also Crimson Octine Swords would basically be useless. I can't really think of anything else though other than something that would prevent the players from switching between swords.

**Comment by MrCompost** [comment]
Oh, how about something like er... you can only use the gem sword that matches the amulet you are wearing? Bit of an odd one but that's all I got atm.

**Comment by TheCyberBrick** [comment]
Why does it seem random? The colors kinda match their effects, red -> fire, green -> health, blue -> defensive

**Comment by TheCyberBrick** [comment]
"Oh, how about something like er... you can only use the gem sword that matches the amulet you are wearing? Bit of an odd one but that's all I got atm."
Who stops you from switching out that amulet? :P

**Comment by MrCompost** [comment]
Well, for a start the fire one doesn't seem to go with the other too. Healing and defense somewhat make sense to me, whilst fire is elemental. As I said, it also makes the octine sword pretty redundant. 

In reply to the second one, nothing, but it'd be clumsy to do in mid battle so you'd have to be more strategic I suppose. I mean, I don't think that's a particularly good idea either though.

**Comment by TripleHeadedSheep** [comment]
If there's going to be a discussion on this, do it in Skype please. My inbox gets spammed

**Comment by TheCyberBrick** [comment]
Shhh Len
I'll just go with what I have already suggested and partially implemented, we can still change it afterwards if we find a better solution

**Comment by vadis365** [comment]
Remove the base fire attack from the octine sword and make it upgradable with the gem?
Also - FU Len - have more spam :P

**Comment by TheCyberBrick** [comment]
Savage monkey doing his job (ง ͠° ͟ل͜ ͡°)ง
I don't see the problem with the octine sword either. We could just increase the fire chance on the octine sword and have it pretty low for the gem, like that the octine sword will still be better than a normal sword with the crimson gem

**Comment by vadis365** [comment]
it could be like a lens foci for the already inherent octine fire and make it a greater chance iir it was something like 1:3 chance to set stuff on fire...

**Comment by vadis365** [comment]
Or make a fancy 'chain' effect that sets other nearby mobs on fire if the gen is active with the base octine sword. it could 'jump' form mod to mob with cool particles in an A.O.E. type thing :P

**Comment by TheCyberBrick** [comment]
The special effect I suggested could look like this:
http://puu.sh/mlZQR.jpg

**Comment by TheCyberBrick** [comment]
I think this is coming along really nicely, I'm sure it'll work well in PvP. The crimson gem now makes the octine sword arguably even more useful than it is now because if you're using the octine sword and the crimson gem procs it causes an AOE like Mr. Monkey suggested.
It also seems quite balanced, for example: you can go all out with aqua gem only armor which will give you a lot of defence when it procs, but you'll be in big trouble when somebody with a crimson gem sword comes along. Same goes for the green gem, you can heal yourself depending on how much damage you're dealing, but if you attack somebody that has a crimson gem armor set you won't deal a lot of damage and also won't heal a lot (if at all).

**Comment by TheCyberBrick** [comment]
Crimson gem: Change fire effect to strong initial knockback and temporary strength buff.
Amulets: Can be applied to tar minions or mud golems. The gem effect would affect the player and not the minion/mud golem. This allows for things like a tar minion that heals the player. Can also be used by the player for a 5th defensive gem.

**Comment by TheCyberBrick** [comment]
Is there anything left except the Amulets?
Also, are there already textures for the amulet?

**Comment by MrCompost** [comment]
The textures are done yeah. Not sure if there is anything else really. We said the amulets would be used on utility mobs right?

**Comment by TheCyberBrick** [comment]
Yes, and the player can also wear one.

**Comment by MrCompost** [comment]
ok

**Comment by TheCyberBrick** [comment]
Amulet is pretty much done. I think only the textures are left

**Comment by TheCyberBrick** [comment]
This is done. Yay :D

**Comment by MrCompost** [comment]
=D
