### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by TripleHeadedSheep** [Angry-Pixel/The-Betweenlands#176]
There will be a special system for the achievements. This is to reward the player more (through collectable trophies) and to make the achievements more interesting than the current Vanilla system (which gets ignored quite often).

First, there will be a base set of achievements to do. These will be the basic things such as entering the BL, getting wooden tools, etc.
Then it will branch out into different categories of achievements. These will be categories such as herblore, combat, mining etc.
Each category has it's own tiers. For completing a tier, the player gets a reward. These could be decorational blocks/items, visually related to that tier. Kind of like trophies.
The rewards should however have no influence on the gameplay itself at all. They are simply just nice rewards to have, collect, and show off.
After the categories there is another set of general achievements, however more advanced such as killing the PW, surviving 3 Blood Sky events, etc.

The set up for the achievements would look a bit like this:
![image](https://cloud.githubusercontent.com/assets/5305563/8965931/c8dfa386-362e-11e5-94c4-03e6bfd596c7.png)

Each achievement can be obtained at any time, so you don't have to do other ones first. It would be unfair if someone did a hard achievement, but doesnt get rewarded because he needs to do other achievements.

**Comment by TheCricket** [comment]
So do you want it in this shape?

**Comment by TripleHeadedSheep** [comment]
Not this shape per se. It is a visual presentation of the structure. However, I sketched a template design and the shape will look quite similar. But if you want it to be different, that's ok.

**Comment by TheCricket** [comment]
I can make any shape you want I was just gonna lay down a template mapping for you so you can change the names and triggers when you have time

**Comment by MrCompost** [comment]
Closed until Len gets back.

**Comment by MrCompost** [comment]
Ok, closed again for now.

**Comment by vadis365** [comment]
Advancements make this no longer a thing.
