### ISSUE TITLE
NPC settlements (Issue is WIP)

### ISSUE THREAD

**Issue by TripleHeadedSheep** [Angry-Pixel/The-Betweenlands#178]
NPCs will spawn in three types of settlements:
- Outpost
- Tribe
- Tribal Village

These settlements are made up by the following buildings:
- Hunting Shack		spawns a hunter
- Fishing Hut			spawns a fisherman
- Small Hut			spawns one villager
- Normal Hut			spawns 2 villagers
- Large Hut			spawns 3 villagers
- Fire pit
- Totem
- Chief Hut			spawns a Tribe Elder and two guards
- Herbalist			spawns a Witchdoctor
- Small Blacksmith		spawns a blacksmith (I)
- Blacksmith			spawns a blacksmith (II)
- Tribe Hall
- Tavern				spawns a bartender
- Burial
- Shaman Hut			spawns a Shaman
- Fighting Pit			spawns a champion
- Guard Hut			spawns two guards
- Market/General Goods	spawns a mechant
_______________________________________________________________________________
Outposts consist of 2-4 buildings, of which atleast 2 are hunting shacks.
Outposts can consist of:
- Hunting Shacks
- Fishing Huts
- Small Huts
- Fire pits
Although NPC settlements are quite rare overall, this type of settlement is most common.

Tribes consist out of 5-8 buildings, of which atleast 3 are normal huts, one is a Chief Hut and one is a totem.
Tribes can consist of:
- Hunting Shacks
- Fishing Huts
- Small Huts
- Normal Huts
- Fire Pits
- Totem
- Chief Hut
- Small Blacksmith
- Herbalist
- Tribe Hall
- Burial
- Fighting Pit
- Guard Huts
Tribes are rarer than Outposts

Tribal Villages consist of 9-15 buildings, of which atleast 2 are normal huts, 2 are large huts, one is a Chief Hut and one is a totem.
Tribal Villages can consist of all the buildings.
These settlements are the rarest of all.
_______________________________________________________________________________
Rules for some buildings:
- Totem			There can only be one per settlement
- Chief Hut		There can only be one per settlement
- Herbalist		There can only be one per settlement, and it will not generate together with a Shaman Hut
- Small Blacksmith	There can only be one per settlement, and it will not generate together with a Blacksmith
- Blacksmith		There can only be one per settlement, and it will not generate together with a Small Blacksmith
- Tribe Hall		There can only be one per settlement
- Shaman Hut		There can only be one per settlement, and it will not generate together with a Herbalist
_______________________________________________________________________________

**Comment by MrCompost** [comment]
Closed until Len gets back.
