### ISSUE TITLE
Add list of random loot items for lootpots

### ISSUE THREAD

**Issue by vadis365** [Angry-Pixel/The-Betweenlands#180]
A list of BL loot items found in the tar pool dungeon's loot pots is needed.

**Comment by TheCricket** [comment]
you want to just allow pack makers to make a custom list?

**Comment by Yulife** [comment]
Well, if they put it in the API like Thaumcraft it'd be possible via MT Integration :)

**Comment by TheCricket** [comment]
or you know make a config

**Comment by MrCompost** [comment]
Right... top = common, bottom = rare

Angler Tooth Arrows (32-48)
Balls of Sap (8-32)

Poisoned Angler Tooth Arrows (8-16)
Weeping Blue Petals (2-8)

Octine Arrows (8-16)
Wight's Heart (1-3)

Basilisk Arrows (8)
Item Scroll

Then of course there's a chance of it spawning a termite.

**Comment by vadis365** [comment]
All very well - but termites will die in the lava pools :P

**Comment by MrCompost** [comment]
You mean tar? =P
That's probably a good point though. Eh, we'll still have them for other dungeons.

**Comment by vadis365** [comment]
Yes tar pools :P
My statement was also correct - they will also die in lava pools. ;)

**Comment by TripleHeadedSheep** [comment]
Silly monkey

**Comment by MrCompost** [comment]
this is still open? BLAM
