### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by TheCyberBrick** [Angry-Pixel/The-Betweenlands#181]
So apparently some people are getting lag from the shaders and it gets worse the longer the game is running.
I've run some tests and RAM, VRAM and CPU usage all seem stable on my pc, nothing suspicous happening. This makes it a bit hard for me to figure out what's causing it.
~~Could anybody else with that problem try to pinpoint which part of the shaders is causing it (portal swirl, blood sky, normal sky, etc.)?
It might just be a stupidly obvious derp on my side, but it's a bit strange that I don't have any of that lag.~~

**Comment by TheCyberBrick** [comment]
Anybody?

**Comment by pau101** [comment]
I'll see what I can find.

**Comment by pau101** [comment]
I don't think it relates to the sky because when I made The Betweenlands generate with no blocks I didn't get lag.

**Comment by pau101** [comment]
I don't think it's caused by the shaders, when I have the shaders disabled from the start I still get the same lag. Although I believe shaders decrease the amount of time it takes for the lag to become noticeable, could possibility relate to memory usage. I'll try with different amounts of allocated RAM.

**Comment by pau101** [comment]
I didn't see a significant change in the lag from changing the allocated memory either higher or lower.

**Comment by vadis365** [comment]
Same thing happening here: #444
Seeing as a lot of code exchange for world-gen has happened, I'll debug The Erebus and report my finding to you guys ;)

**Comment by vadis365** [comment]
Looks like it may be The Erebus custom spawn code causing some problems for us and as BL uses the basic vanilla spawning code these two issues may not be related after all.

**Comment by TheCyberBrick** [comment]
We do have some custom mob spawning stuff, but that's only active during the Blood Sky or Spook event. When I implemented it I also ran some tests to see if it affects performance but didn't notice any lag

**Comment by TheCyberBrick** [comment]
I can't fix this because I'm not getting it

**Comment by MrCompost** [comment]
I used to get it, I don't any more. One thing that IS causing me lag now is the sky lighting though. It's not that bad but we probably ought to have an option to disable it somewhere.

**Comment by TheCyberBrick** [comment]
No, adding a config option for the lighting is a bad idea because it messes up the world when you change it. Also, it's pretty much fixed after installing Optifine.
Might be related to a vanilla bug:
- https://bugs.mojang.com/browse/MC-44801
- https://bugs.mojang.com/browse/MC-55467
- https://bugs.mojang.com/browse/MC-44801
- http://forums.teamextrememc.com/index.php?/topic/22158-about-chunk-ticking-client-lag/

**Comment by MrCompost** [comment]
Ah ok

**Comment by TripleHeadedSheep** [comment]
Gonna test this now
