### ISSUE TITLE
Music and ambient sounds broke

### ISSUE THREAD

**Issue by TripleHeadedSheep** [Angry-Pixel/The-Betweenlands#191]
It happened during a bloodSky while Spook was active. At first it worked fine, but when I entered the world again suddenly there were no ambient sounds or music. Had to restart the game.

**Comment by TheCyberBrick** [comment]
Pls len, stahp causing problems pls

**Comment by TripleHeadedSheep** [comment]
Got a problem with that?!

**Comment by TheCyberBrick** [comment]
Anybody ever been able to reproduce this?

**Comment by MrCompost** [comment]
I've never had this issue.

**Comment by MrCompost** [comment]
Don't even know what this is.

**Comment by TripleHeadedSheep** [comment]
Had it a while ago again. Now also music starts playing when I have it on off. When I put it up again and off again, it still starts playing.

**Comment by TheCyberBrick** [comment]
Is this still a thing? Not having that problem

**Comment by MrCompost** [comment]
I've never had it either, nor do I no how to replicate it.

**Comment by TheCyberBrick** [comment]
We can have a look at this later
