### ISSUE TITLE
New cave stone

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#193]
Limstone caves - kinda like really big ore patches I suppose, not whole biomes
Pitstone - A new stone type that generates about 20 blocks or so above whatever the cave water level is. We could have a new Valonite ore block set in this stone instead of in Betweenstone. Same with Life Crystals, though I think they should have a new little model so they stick out of blocks or something and only gen under the water.

**Comment by TheCyberBrick** [comment]
Some more cave info:
- 'Dense fog' event shouldn't affect fog in caves
- Marsh fog shouldn't affect fog in caves
- Fog clears up again once below the Pitstone layer
