### ISSUE TITLE
Core mod MP bug

### ISSUE THREAD

**Issue by TheCyberBrick** [Angry-Pixel/The-Betweenlands#194]
This is likely a core mod bug as it wasn't happening when I disabled the core mod and the crash log doesn't mention the BL anywhere.

---- Minecraft Crash Report ---- // You're mean.
Time: 10/20/15 11:53 PM Description: Exception in server tick loop
java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP at net.minecraft.server.management.ServerConfigurationManager.func_148545_a(ServerConfigurationManager.java) at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:101) at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:60) at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:215) at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityClientPlayerMP at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) at java.lang.ClassLoader.loadClass(Unknown Source) at java.lang.ClassLoader.loadClass(Unknown Source) ... 10 more Caused by: java.lang.NullPointerException at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ... 12 more

**Comment by vadis365** [comment]
client method being called on the server side somewhere mate...

**Comment by TheCyberBrick** [comment]
I'm pretty sure it is the code mod injecting code that uses EntityClientPlayerMP in a server side class because it wasn't happening when I used the wrong build script (which exluded the core mod). Now with the correct build script that includes the core mod this bug is happening
