### ISSUE TITLE
Herblore

### ISSUE THREAD

**Issue by TheCyberBrick** [Angry-Pixel/The-Betweenlands#195]
**How it works:**

1. Aspects are randomly distributed to items among tiers and groups. The distribution depends on the world seed
2. Aspects themselves don't have a defined effect, only a classification of what they could affect
3. Aspects always have the same classification. This does not depend on the world seed
4. Aspects have a certain effect (derived from previously mentioned classifications) on geckos, e.g. nausea, sweat etc. 
(this is only for the gecko test, it does NOT affect the potion effect in the end)
5. Doing the gecko test gives the HL book an entry with the found effects and their corresponding aspects that caused it
(and the strength of the occurred effects, hinting at the amount of the corresponding aspect)
6. Certain combinations of aspects yield functioning potions, some don't
7. The aspect Byariss (corruption) creates the negative counterpart of a potion if it's in the brew
8. Even numbers of ingredients with Byariss cause the outcome to have a positive effect, odd numbers cause the outcome to have a negative effect
9. The amount of Byariss doesn't affect the outcome, only the presence matters
10. Ingredients can be mixed in an infuser and yield a bucked with the infusion. Only a limited amount of ingredients can be mixed in the infuser
11. The infusion can be distilled in an alembic and retrieved with glass bottles
12. The resulting amount of potions depends on the sum of all amounts of the mixed aspects
13. Strength and duration are affected by the amount of two aspects for strength and duration. Which aspects affect duration and/or strength depends on the potion recipe.
14. Normal potions have a fixed recipe that doesn't depend on the world seed. Which aspects affect strength and/or duration of the potion is mentioned in the potion recipe.
15. Special potions have a random recipe that depends on the world seed
16. Recipes for said special potions can be found as loot and will add a HL entry when read
17. The HL book (with all the entries) can be copied and given to other players
18. Common ingredients usually have multiple different aspects. Less common ingredients have less aspects, but higher amounts
19. Aspects can be isolated by distilling an infusion in the alembic (unless the combination of the aspects is that of an elixir recipe and the infusion time is correct)
20. Isolating aspects comes with a loss

------------------------------------------------------------------------------------------------------------------------

**A List of aspects:**

-iis -> Psychological or philosophical aspects.
-ynn -> Aspects related to the physical body.
-az -> Magical aspects.
-en -> Aspects who have (a magical) influence on the physical world.
-un -> Substances.

*Basic aspects:*

Tier I:
- Ordaniis - Enhance - (Needs new effect)

- Celawynn - Stomach - Has effect on the stomach. So this could have effect on the hunger bar for example.

- Yeowynn - Health - Has effect on the health bar, could be both negative or positive, depending on the combination.

- Azuwynn - Muscle - Has effect on the muscles, could either result in more damage, speed or maybe rapid fire and all stuff in that regard.

Tier II:
- Freiwynn - Vision - Alters the player's vision (in combination with other properties. So for example when you combine health with vision, you would be able to spot mobs their health).

- Dayuniis - Mind - Has effect on the player's mind and on how senses work.

- Fergalaz - Earth - Magical property which relates to earth. Any combination with this effect can be related to the element earth.

- Yunugaz - Wind - Magical property which relates to wind. Any combination with this effect can be related to the element wind.

- Firnalaz - Fire - Magical property which relates to fire. Any combination with this effect can be related to fire.

- Byrginaz - Water - Magical property which relates to water. Any combination with this effect can be related to water.

- Armaniis - Desire - Has effect on the desires of a mob or the player. Could be useful for food, but also things like trading or corrupting the desire.

Tier III:
- Geoliirgaz - Void/Darkness - Magical property which relates to the void or ether. Any combination with this effect can be related to void or darkness.

- Yihinren - Form - This effect has influence on the form of things, both physical and psychological. A very rare aspect that is mainly used in the special potions.

*Special aspects:*

Tier I:
- Byariis - Corruption - This effect can corrupt the effect of a potion. So it could turn negative into positive, and positive into negative.

------------------------------------------------------------------------------------------------------------------------

**Potions:**

Tier I:
- *1* Elixir of Strength:
Increases dealt damage
*Muscle, Enhance*

- *2* Nimblefeet Elixir:
Increases player's speed
*Muscle, Enhance, Wind*

- *3* Elixir of Healing:
Heals the player over time
*Health, Enhance*

- *4* Elixir of Ripening:
Heals decay over time
*Health, Enhance, Mind*

- *5* Toughskin Elixer:
Disables any damage by plants
*Muscle, Health, Stomach*

- *6* Elixir of Feasting:
Refills hunger bar over time
*Stomach, Health, Enhance*

Tier II:
- *7* Hunter's Sense Brew:
Allows the player to see 'scent' trails of mobs
*Vision, Mind, Enhance, Fire*

- *8* Masking Brew:
Hides the player from mobs up to a 2 block range
*Mind, Desire, Corruption*

- *9* Swiftarm Brew:
Trigger happy arm (for both swing and use of bow)
*Muscle, Mind, Wind, Enhance*

- *10* Brew of the Cat's Eye:
Night vision effect
*Vision, Mind, Enhance, Void/Darkness*

Tier III:
- *11* Draught of Sagittarius:
Allows the player to 'see' a line of where his arrow will land
*Vision, Mind, Corruption, Enhance, Desire*

- *12* Spiderbreed Draught:
Allows to player to climb vertical walls as if they were ladders
*Muscle, Earth, Mind, Form, Wind*

- *13* Lightweight Draught:
Allows the player to walk on water and jump 2 high
*Muscle, Water, Wind, Form, Void/Darkness*

- *14* Draught of the Unclouded:
Removes fog for the player
*Mind, Vision, Void/Darkness, Enhance, Wind*

*Special potions:*

- *15* Shapeshifter's draught of Gillsgrowth:
Transforms the player into a fish, allowing him to swim fast and breathe underwater
*Atleast Form and Water*

- *16* Shapeshifter's draught of Wings:
Transforms the player into a Dragonfly, allowing him to fly, but beware of Lurkers!
*Atleast Form and Wind*

- *17* Hunter's Sense Masterbrew:
Allows the player to spot mobs through blocks
*Atleast Form and Mind*

------------------------------------------------------------------------------------------------------------------------

**Anti Potions:**

Tier I:
- *1* Elixir of Weakness:
Reduces dealt damage

- *2* Lumbering Elixir:
Decreases the player's speed

- *3* Elixir of Draining:
Drains the player's health over time

- *4* Elixir of Decay:
Drains the player's decay faster

- *5* Poisonsting Elixir:
Poisons the player (or maybe insta poison whenever he touches a plant)

- *6* Elixir of Starvation:
Drains the player's hunger faster

Tier II:
- *7* Drunkard's Brew:
Causes heavy nausea

- *8* Stenching Brew:
Spotting range of mobs increases by 8

- *9* Slugarm Brew:
Decreases the speed of swings and bow use of a player

- *10* Blindman's Brew:
Blinds the player (maybe even worse than Vanilla)

Tier III:
- *11* Weakbow Draught:
Arrow range is about 3 blocks...

- *12* Basilisk Draught:
Stuns the player (same effect as Basilisk Arrows)

- *13* Heavyweight Draught:
Players cant swim and sink in mud even with rubber boots

- *14* Draught of the Fogged Mind:
Almost the same as blindness, it puts a very dense fog around the player

*Special potions:*

- *15* Shapeshifter's draught of the Deformed:
Deforms the player and causing him to suffocate

- *16* Shapeshifter's draught of the Limbless:
Removes the player's limb, disabling him from many movement, clicking or use of items. It also does a bit of damage over time

- *17* Masterbrew of Isolated Senses:
Blinds the player, mutes mob sounds and causes slight nausea

**Comment by TripleHeadedSheep** [comment]
Here are the aspects that increase strength and duration. Strength comes first, then duration. The anti-potions use the same aspects.

Elixir of Strength:
Muscle - Enhance

Nimblefeet Elixir:
Wind - Enhance

Elixir of Healing:
Health - Enhance

Elixir of Ripening:
Mind - Enhance

Toughskin Elixir:
Health - Stomach

Elixir of Feasting:
Stomach - Enhance

Hunter's Sense Brew:
Vision - Mind

Masking Brew:
Desire - Mind

Swiftarm Brew:
Muscle - Enhance

Brew of the Cat's Eye:
Vision - Mind

Draught of Sagittarius:
Vision - Mind

Spiderbreed Draught:
Muscle - Form

Lightweight Draught:
Wind - Form

Draught of the Unclouded:
Void - Mind

Shapeshifter's Draught of Gillsworth:
Water - Form

Shapeshifter's Draught of Wings:
Wind - Form

Hunter's Sense Masterbrew:
Mind - Form

We probably need to playtest this often to see if it is balanced

**Comment by MrCompost** [comment]
Ok so, how much is left to do with this? It's looking pretty complete to me =)

**Comment by TripleHeadedSheep** [comment]
Yup :)
We still need the manual though, and we need to have a look at the special potions. If they are going to be in the first release or not.

**Comment by MrCompost** [comment]
Ah ok

**Comment by TripleHeadedSheep** [comment]
Get dat booty of yours on Skype pretty please

**Comment by MrCompost** [comment]
Sorry, I'm going out in like half an hour got stuff to do

**Comment by TripleHeadedSheep** [comment]
Ok, I'll delete these messages now.
When you get back, we got something to discuss regarding the first release

**Comment by TripleHeadedSheep** [comment]
This is done, except fot the special infusions, but we will do those later
