### ISSUE TITLE
Sickness... of... food? or something?

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#196]
If the player eats a certain number of one type of food, they will not be able to eat any more for a period of time. Instead a message will pop up saying something like - "(Player name): Ugh... I can't eat any more of this." This will basically prevent the player from relying on one source of food constantly. 

Write ideas for messages down below :P

**Comment by Sevenoon** [comment]
I was thinking, maybe there should be various different things the player could say, some being rare, while others being references to other famous media. It's just a little fun thing I thought of. But here's some stuff I thought up of.

"This food has tainted your appetite."
"Ugh... I can't eat anymore of this."
"There's gotta be something else to eat."
"I need some new flavors"
"How about no."
"I'm in the mood for something like (food name)"
"This is disgusting- no more."

**Comment by MrCompost** [comment]
Some things like that are ideal. I also kinda wanted to slip in some funny references too.

**Comment by MrCompost** [comment]
This looks pretty much done to me. How is it, Lex?

**Comment by iLexiconn** [comment]
It kinda works already, but it's not finished yet.

**Comment by TheCyberBrick** [comment]
Lex, are you going to finish this?

**Comment by MrCompost** [comment]
Lex, if you can't find the time to do the two new features you said then just at least finish off the unfinished things please.
