### ISSUE TITLE
BetweenLands Crashed When Flying Around 

### ISSUE THREAD

**Issue by jredfox** [Angry-Pixel/The-Betweenlands#200]
Version TheBetweenlands-1.7.10-1.0.0-alpha.1-build.104-universal
Crash Report: http://pastebin.com/fUx1zC6B
hs_err_pid1252.log : http://pastebin.com/5FrEXgdN

I was flying around thebetweenlands with only your mod optifine and the tardis mod so I could easily  go there there faster. Everything was going fine then The game I noticed started allocating more ram. Later the game just crashed but, didn't even generate a crash report it just stopped running then I physically had to control a and paste the crash to pastebin.  I also made sure there was no biome and dimension conflicts. I was only flying around for about 10-15 minuets.

I got a very similar crash on the latest public alpha build. it was about 20 minuets in game then I hit f 11 it freaked out the screen went gray and then it crashed.  
Pastebin: http://pastebin.com/RFH03jR1

**Comment by pau101** [comment]
Can you provide C:\Users\jjred\AppData\Roaming\.minecraft\hs_err_pid1252.log?

**Comment by jredfox** [comment]
I found the file you were looking for but, it wasn't in the crash reports folder. You may now read it.

**Comment by pau101** [comment]
Can you check if your graphics card is up to date?

**Comment by jredfox** [comment]
It is up to date. I have windows 10 Intel hd graphics laptop. My computer doesn't support shaders nor does any laptop out there however the shaders mod was not installed. Updating your graphics software does nothing if your computer doesn't support shaders which only like desktops support so I have heard. I also heard you could get an external graphics card so your laptop could support shaders. I don't have 200 bucks to buy one though. I don't see why your mod would have to require shaders in order for it to not crash in 25 minuets later in game.  I think this is a java error.  From what I heard from The_WeatherPony It might be a bug from java itself or I think it might also be the mod doing something either to activate the bug or some code that my computer doesn't support. This is a brand new laptop. I have 8g of ram.

**Comment by TheCyberBrick** [comment]
If you think it has to do with the shaders you can disable them in the config (if you haven't already done that). They're not required, they mostly just enhance the mod's ambience. The Intel graphics drivers are known to sometimes cause issues, especially with shaders.

**Comment by jredfox** [comment]
I don't think it has to do with shaders I think it has to do with your mod doing something for java to do a core mini dump which is not supported. I think your mod has activated a bug with java itself or something java doesn't support. This bug was in for awhile railcraft mod from 1.4.2-1.4.7 and I tested it in 1.7.10 and it was fixed. This issue needs to be fixed by it's release.

**Comment by TheCyberBrick** [comment]
This error is very likely caused by a driver crash (specifically "ig8icd64.dll" which is your Intel HD graphics driver). It's hard to fix such an error because you don't really know what exactly is causing it. If you could somehow identify what is causing it (e.g. a certain entity, a block etc.) we could try to fix it

**Comment by TheCyberBrick** [comment]
Actually now that I had a second look at the crash log, it looks like the last thing that's happened before the crash has to do with Optifine expanding the Tessellator buffer ([OptiFine] Expand tessellator buffer, old: 1048576, new: 2097152) and the core dump shows that the last operation was the Tessellator trying to draw a buffer (net.minecraft.client.renderer.Tessellator.func_78381_a()). Could you try it again without Optifine and see if it still crashes?

**Comment by jredfox** [comment]
I would have to fly around for 30m but, sure

**Comment by TheCyberBrick** [comment]
I'm not getting that error and it hasn't been reported by anyone else either. So if you want this to be fixed for you I can expect some help from you as well ;)

**Comment by jredfox** [comment]
Well no one else flyed around for 30m I will test this today without optifine relax .

**Comment by jredfox** [comment]
ok I can't even get to the dimension without optifine. My computer cannot proccess anything it lags at 1fps and I can't do anything. I put it on 4g and it only used 250mb. I physically cannot test this without optifine however I could try the same thing again and again. Can you please go with a seed of 2 and fly around nearly in one dirrection for 25m? If you get a crash without optifine within 30m then it's settled. Even if it's optifine it needs to be compatible or I can't use it at all like no cubes mod.

**Comment by pau101** [comment]
If you use only Optifine and The Betweenlands do you experience this crash?

**Comment by jredfox** [comment]
I got a very similar crash on the latest public alpha build. it was about 20 minuets in game then I hit f 11 it freaked out the screen went gray and then it crashed.

Pastebin: http://pastebin.com/RFH03jR1

**Comment by TheCyberBrick** [comment]
Hmm, I'm not getting that crash even with Optifine installed. You also have many other mods installed, could you check if the crash still occurs without any of those other mods?

**Comment by jredfox** [comment]
the only other mod I had was the dalek mod and I configed the dimensions and biomes out of the way so there would be no conflicts maby the error has fixed itself?  try it with the dalek mod avoid these ids 51-62 are the biome ids for the dalek mod besides that the configs of dimensions are also off make sure you config them and you are good to go.

**Comment by TheCyberBrick** [comment]
You definitely had other mods installed as well:
"Client attempting to join with 10 mods : CodeChickenCore@1.0.7.47,NotEnoughItems@1.0.5.111,Waila@1.5.10,FML@7.10.99.99,antiidconflict@1.3.5,weaponmod@v1.14.3,Forge@10.13.4.1558,thebetweenlands@1.7.10-1.0.0-alpha.1-build.132-1.0,mcp@9.05,thedalekmod@39.75"
Could you please try it out *without* those mods installed (except forge, mcp and betweenlands of course)?
Also, has the error you originally posted ever happened again with the latest build?

**Comment by jredfox** [comment]
no but, I havn't tested it for 25 minuets

**Comment by jredfox** [comment]
I will test it just with forge betweenlands optifine .

**Comment by TheCyberBrick** [comment]
I'll just assume that his is solved as there isn't any response
