### ISSUE TITLE
Weed Wood Boats Are Unstable 

### ISSUE THREAD

**Issue by jredfox** [Angry-Pixel/The-Betweenlands#202]
Version: TheBetweenlands-1.7.10-1.0.0-alpha.1-build.104-universal
Images: http://imgur.com/a/A8rb1

I started to test out the boat when it lagged and first didn't place it in the water. I then proceeded to place it on land and I kept getting an open gl errors that said stock overflow when placing down a boat. **1283 open gl error**. I then tried to ride the boat I couldn't see how to move forward with the controls it gave me. I could be mistaking for the controls I could only row right and left. *I then tried to get out of a boat and some entities appeared everywhere floating in my face and came from different directions. The only way to fix this was to kill yourself.* In the third picture it was taking the dirt texture and messing with it to when I was by the shore and there was dirt and grass blocks (not the grass blocks plants).

**Comment by pau101** [comment]
Weedwood Rowboats are very WIP.

**Comment by jredfox** [comment]
Ok cool.  Why did you close this issue before the entities bugs open gl bugs are even fixed? If you close the issues before they are fixed you might forget that they exists and I labeled everything I could find on the boats bugs.

**Comment by pau101** [comment]
The problems that exist aren't one with The Betweenlands. I'm nearly 100% certain your graphics driver doesn't support color masking. With vanilla Minecraft try enabling 3D Anaglyph in the Video Settings and tell me what happen. You should try seeing if there is an update to your graphics driver.

**Comment by jredfox** [comment]
My graphics driver was made this year. I am good your mod is too op for any laptop. You need to add support so it doesn't crash with laptops because, not alot of people have desktops including my pc.

**Comment by pau101** [comment]
It being made this year does not guarantee your graphics drivers are up to date. What happens with vanilla 3D Anaglyph?

**Comment by pau101** [comment]
The latest version of your graphics driver is 15.40.10.4300, you currently have 10.18.15.4240
The download is available [here](https://downloadcenter.intel.com/download/25484/Intel-Graphics-Driver-for-Windows-7-8-1-10-15-40-).

**Comment by TheCyberBrick** [comment]
Intel graphics drivers are known to cause errors with OpenGL so don't simply put the blame us. We've already had multiple reports from players with Intel graphics, but those issues could always be resolved by disabling the shaders. You could also try disabling "Advanced OpenGL" in the options menu and see if that fixes anything.
