### ISSUE TITLE
HL Plant Drops

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#203]
~~1. fallen leaves don't drop anything when broken with either tools~~

~~2. I reckon that the bush should drop weedwood sticks when harvested with the sickle and of course itself with the shears~~

~~3. weeping blue drops nothing when harvested with the sickle~~

~~4. nor does the pitcher plant (needs texture)~~

~~5. tall cattail drops nothing when broken with sickle~~

~~6. swamp reeds just always drop the swamp reeds item (intended)~~

~~7. as does swamp kelp (intended)~~

~~8. water weeds drop nothing when broken with sickle (needs texture)~~

9. water flowers never drop anything (though they do just suck)

~~10. generic swamp plants don't drop anything when broken with the sickle, but I don't really think 
they need to, being generic and all. maybe we should just add a general leaf item that's dropped by a bunch of things~~

11. venus fly trap plant drop & ground item need texture

12. volarpad plant drop & ground item need texture

13. thorns plant drop & ground item need texture

14. poison plant drop & ground item need texture

~~15. moss drops nothing when broken with shears~~

~~16. lichen drops nothing when broken with shears~~

~~17. cave moss drops nothing when broken with shears~~

~~18. cattail (not double) nothing when broken with sickle (wot? working just fine)~~

~~19. swamp tallgrass (not double) drops nothing when broken with sickle~~

~~20. milkweed drops nothing when broken with sickle~~

~~21. dead weedwood bush drops nothing when broken with sickle (should drop weedwood sticks imo)~~

~~22. the hangers plant drop & ground item need texture~~

Numbers 1,4,8,9 (ugh don't know what to do with this thing), 10 (same thing as 1), 11, 12, 13 and 14 need textures doing.

**Comment by TheCyberBrick** [comment]
Should all be done

**Comment by MrCompost** [comment]
Awesome :D
