### ISSUE TITLE
Herblore - Gecko Testing

### ISSUE THREAD

**Issue by TripleHeadedSheep** [Angry-Pixel/The-Betweenlands#206]
You discover the aspects of a plant by testing it on a gecko.

First, you have to capture a gecko with a net and put it in a cage (still to be implemented).
Once you put the gecko inside the cage, you can test any ground item on it (right click).
Right click again to analyse the gecko's appearance or behaviour. 
This will send a message to the player through chat, which tells him about the aspect discovered, that his Herblore Book has been updated (if the player has one in his inventory) and that, when a plant has multiple aspects, there might be more to the plant.
When a plant has multiple aspects, the aspects will be discovered in order.
The gecko has a short cooldown before you can test on it again.
_____________________________________________________________________________
Gecko responses on Aspects:

Ordaniis - Enhance:
The gecko's scales seem to be glowing slightly. This ingredient seems to have the aspect Ordaniis.

Celawynn - Stomach:
You can hear its belly rumbling and it seems to burp a lot. This ingredient seems to have the aspect Celawynn.

Yeowynn - Health:
You've never seen a healthier gecko, it's bursting with energy. This ingredient seems to have the aspect Yeowynn.

Azuwynn - Muscle:
You can see its muscles twitching uncontrollably. This ingredient seems to have the aspect Azuwynn.

Freiwynn - Vision:
Its eyes are pulsating. This ingredient seems to have the aspect Freiwynn.

Dayuniis - Mind:
The gecko is walking around like a drunkard and looks around in a schizophrenic manner. This ingredient seems to have the aspect Dayuniis.

Fergalaz - Earth:
The gecko's scales seem to become rock hard, it can barely move. This ingredient seems to have the aspect Fergalaz.

Yunugaz - Wind:
The gecko seems light, and its breath sounds like a hollow wind. This ingredient seems to have the aspect Yunugaz.

Firnalaz - Fire:
Its scales have a red glow and it breathes a hot breath. This ingredient seems to have the aspect Firnalaz.

Byrginaz - Water:
It's drooling, sweating and peeing around its cage. This ingredient seems to have the aspect Byrginaz.

Armaniis - Desire:
It seems very calm and looks at you with loving eyes. This ingredient seems to have the aspect Armaniis.

Geoliirgaz - Void/Darkness:
The gecko has an empty look in its eyes and doesn't seem to respond to anything. This ingredient seems to have the aspect Geoliirgaz.

Yihinren - Form:
Its scales became puffy and its head looks... different. This ingredient seems to have the aspect Yihinren.

Byariis - Corruption:
The gecko is chewing furiously on its tail and looks around as if possessed. This ingredient seems to have the aspect Byariis.

Cooldown message:
You need to wait for the previous effects to wear off, before you can test this ingredient.

Multiple Aspects message:
The might be more to this ingredient.
_____________________________________________________________________________
The amount of which an aspect is present in an ingredient will be shown in the HL book.

Lastly, there are different models and textures for the geckos to correlate to the analysis.

**Comment by TheCyberBrick** [comment]
I think this is all finished
