### ISSUE TITLE
[Suggestion] Alligators/More Swamp Creatures

### ISSUE THREAD

**Issue by jredfox** [Angry-Pixel/The-Betweenlands#207]
[Suggestion] Alligators/More Swamp Creatures.  I would like to see an alligator and or crocodile in the swamps since that is a symbol of the swamps.  I would also like to see some sword of alligator snapping turtle. Maby some cryptids or mythological swamp creatures to like the lizard man?  something cool amazing swampy scare your pants off creatures.

**Comment by TripleHeadedSheep** [comment]
Not gonna happen. Alligators were replaced by lurkers. For now we wont add any new creatures as we have other priorities for the release.
I don't know who you are, but if you have suggestions, don't post them here please. The issues posted here are purely for dev.

Can someone close this issue? Apparently I can't do that this time x)
