### ISSUE TITLE
Elixirs

### ISSUE THREAD

**Issue by TheCyberBrick** [Angry-Pixel/The-Betweenlands#208]
I need to know the base duration and maximum duration of each elixir. I think that the negative ones should last generally a lot shorter than the positive ones (e.g. petrify or blindness for minutes would be op suck a lot). Some positive ones e.g. Feasting and Ripening should last quite a while (or at least their maximum duration should be pretty high).

**Comment by TripleHeadedSheep** [comment]
My idea is:

Tier 1 - Base 3 minutes - max 8 minutes

Tier 2 - Base 2 minutes - max 6 minutes

Tier 3 - Base 1 minute - max 5 minutes

Special ones - Base 1 minute - max 4 or 3 minutes

Negative:

All - Base 20 seconds - max 2 or 1.5 minutes
