### ISSUE TITLE
Server crash- Hitting a mob while flying in a TARDIS from TARDIS mod.

### ISSUE THREAD

**Issue by ProsperCraft** [Angry-Pixel/The-Betweenlands#210]
at thebetweenlands.event.entity.MiscEntitySyncHandler.sendToWatchingEntity(MiscEntitySyncHandler.java:36)

http://pastebin.com/JmZWtcYj

**Comment by ProsperCraft** [comment]
Not just sheep-

http://pastebin.com/s22SH4Qg

**Comment by TheCyberBrick** [comment]
The latest commit should fix this. Could you try it out again (assuming you can compile the mod yourself)?

**Comment by ProsperCraft** [comment]
Can you send it through your jenkins build server?
