### ISSUE TITLE
Random pots in caves

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#211]
Pots of Chance can be found scattered around caves. Their drops are as follows - 

In order from most common to rarest

Angler Tooth Arrows (32-48)
Balls of Sap (8-32)

Poisoned Angler Tooth Arrows (8-16)
Weeping Blue Petals (2-8)

Octine Arrows (8-16)
Wight's Heart (1-3)

Basilisk Arrows (8)
Item Scroll

There is also a chance of them just spawning a Termite when broken.

**Comment by TripleHeadedSheep** [comment]
Bart finished this. Have we already set the items for the Item Scroll?
Closing this for now, I'm cleaning up issues ;)

**Comment by MrCompost** [comment]
Ah, great! I don't believe so.

**Comment by MrCompost** [comment]
Hey man, just looked at the commit and it looks like you've used the tar pots instead of the normal ones. That'll look pretty weird. Also I can't really tell but you may wanna make them less common, that number looks a bit too high. Cheers.

**Comment by MrCompost** [comment]
Oh, sorry I've not been around today btw. Busy busy busy!

**Comment by TripleHeadedSheep** [comment]
The number seems fine, could be a bit lower, but it's not easy to find them. Although they are very common near cave entrances somehow :/
But indeed, they are the tar pots :P

**Comment by vadis365** [comment]
What you need is: lootPot1, lootPot2, lootPot3
Not: tarLootPot1, tarLootPot2, tarLootPot3

**Comment by TripleHeadedSheep** [comment]
Why don't you come and help out a bit? ;)

**Comment by vadis365** [comment]
Because I'm retired :P

**Comment by TripleHeadedSheep** [comment]
Retired folk need a hobby to keep them busy :3

**Comment by vadis365** [comment]
Just fix the code and I'll call it a win :)

**Comment by TripleHeadedSheep** [comment]
Very tempted to, how do I edit? It says I'm not in the branch or something (I'm gonna break stuff)

**Comment by vadis365** [comment]
Then don't. Let one of the grown-ups do it Len :P

**Comment by TripleHeadedSheep** [comment]
But I wanna win :'(

**Comment by imdutch21** [comment]
done?

**Comment by vadis365** [comment]
Could do with a check that doesn't just involve top side of a solid block.
Maybe use the methods I added for checking if it is dirt or rock or something?
That would stop the rare (and silly looking) gen of pots on top of tree roots and stalagmites.
