### ISSUE TITLE
Weedwood Rowboat being weird

### ISSUE THREAD

**Issue by TripleHeadedSheep** [Angry-Pixel/The-Betweenlands#212]
Ok so there are a few issues with the rowboat:

1. Sometimes it stops. It just freezes movement and animation. If I remember correctly, this mostly happens when I try to turn and then suddenly turn the opposite direction.

2. Sometimes it launches itself (horizontally). I think this might be due some entities nearby pushing it when I get out. But I'm not too sure. When it happened a few times, there were anglers and fireflies in the area.

3. Anglers and lurkers can get in. Although this is quite funny, it's a bit of a problem because their models dont render, so I dont see them in the boat.

**Comment by pau101** [comment]
The first one is server stutter from terrain generation.
How far does it launch? I couldn't get it to move at a fast speed by exiting it.
I just made the change so entities don't hop into rowboats 3205e16.

**Comment by TripleHeadedSheep** [comment]
It went about 30 blocks is my guess.

Also, about the terrain gen. I'm not sure, but I do believe I already generated those parts. Also, only the boat froze. Mobs and particles still did their thing. I'll test again today, see if I can reproduce it.

**Comment by pau101** [comment]
The rowboats freeze because their animation is driven by the server, most mob and particle animation can happen without the server.

**Comment by TripleHeadedSheep** [comment]
Even movement?

**Comment by pau101** [comment]
Of mobs?

**Comment by TripleHeadedSheep** [comment]
Yes.
Although I'm not 100%, I do recall some anglers still swimming. I still have to reproduce the bug, will have a look then, to be 100% sure.

**Comment by TripleHeadedSheep** [comment]
Havent encountered this for a while, even when I tried to reproduce it. Will close it.
