### ISSUE TITLE
Volarpad Kite/Glider thing... whatever.

### ISSUE THREAD

**Issue by vadis365** [Angry-Pixel/The-Betweenlands#213]
What is this supposed to do?
What has been done so far?
What needs doing to it?

All information regarding this feature would be appreciated.

**Comment by imdutch21** [comment]
It basicly  works, but the model is screwed up

**Comment by vadis365** [comment]
Done. - I don't like this much, it should have a custom model and render on the player not in their hand.
meh.

**Comment by vadis365** [comment]
I think this needs to be re-done.
The model is just a copy of the volarpad block which is lovely as a plant...
Whilst using the player looks really derpy in 3rd person - the kite is held and swings with the player animation. Why not remove the held animation and render it on the player with a new model like a parachute/hang glider type thing? It could still be the selected item in the hot bar, that would mean all you could do is glide. For future enhancement you could make it craftable with an armour chestplate which would then free up the player's hands for a bow or something. I would be willing to make the 1st part of this (for now) if a new model is provided - it wouldn't take long to implement as it is mainly just a change in the rendering.

**Comment by TripleHeadedSheep** [comment]
Still need to decide whether it will be more of a parachute or a glider... Since the BL doesn't do much with terrain height, except for the trees, I'm not sure how useful either of those will be

**Comment by vadis365** [comment]
Triple - gimme a new model ffs.
If not I'll make something - and you will forever hate the fact you didn't make it :P

**Comment by TripleHeadedSheep** [comment]
Will come somewhere this week with a bit of luck

**Comment by MrCompost** [comment]
New model done, not implemented.
Currently cannot be obtained. Need to decide upon a crafting recipe.
