### ISSUE TITLE
Loot for dungeon chests

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#215]
Referring to any loot chest in a structure.

 - Common

Sulfur 8-16
Lurker Skin 2-4
Reed Rope 4-8
Angler Tooth 4-8
Swamp Reed Parchment 4-8
Ball of Sap 8-32

- In-between (hehe)

Syrmorite Ingots 4-16
Octine Ingots 4-16
Pink Marshmallow 1 
Green Marshmallow 1
Donut 2-4
Jam Donut 2-4

- Rare

Valonite Shard 1 -4
Angry Pebble 8-16
Item Scroll 1-3
Middle Fruit Seeds 1-8
Aspectrus Seeds 1-8
Any music disc 1

- Very Rare

Forbidden Fig 1
Explorer's Hat 1
Voodoo Doll 1-3
Ring of Power 1
Swift Pickaxe 1
Wight's Bane 1
Skull Mask 1
Tribal Pants 1

**Comment by imdutch21** [comment]
is this also for the small ruïn like structures?

**Comment by MrCompost** [comment]
Oh, yeah. Dave said he was going to make a class for it I think. Also as a heads up, I'm very busy this week until Friday so I may or may not be around.

**Comment by vadis365** [comment]
Bart added this list and I have moved it to a class of it's own for use whenever a basic loot chest is needed. Closing because, well, it's done.
