### ISSUE TITLE
Swamp Hags have no heads!

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#216]
http://i.imgur.com/5w3ICSQ.png

WTF?!

**Comment by TheCyberBrick** [comment]
lol

**Comment by vadis365** [comment]
Blame @iLexiconn or @BobMowzie for this :P

**Comment by BobMowzie** [comment]
I hadn't touched them before this showed up...

**Comment by vadis365** [comment]
@BobMowzie - I was having a jk - we all know it was @iLexiconn that broke them ;)

**Comment by iLexiconn** [comment]
thank

**Comment by vadis365** [comment]
np - now fix it :P

**Comment by TheCyberBrick** [comment]
Is this still not fixed?

**Comment by MrCompost** [comment]
Nope. Bart had a quick look but couldn't find anything.

**Comment by iLexiconn** [comment]
I really don't know what's causing this.

**Comment by MrCompost** [comment]
Yeeees thank you Paul <P

**Comment by iLexiconn** [comment]
Rip the headless release dream :^)
