### ISSUE TITLE
Wight Tower Dungeon

### ISSUE THREAD

**Issue by vadis365** [Angry-Pixel/The-Betweenlands#217]
Feel free to edit this. I will be working on what Oli and myself have so far.
This dungeon will be a slightly larger mini-dungeon of sorts.
Not boss worthy but bigger and a bit tougher than the smaller dungeons we have so far.

Tower to be fairly large, enough to fit a couple of spawners and chests/loot pots etc.
Foot print of a maximum of 16x16 to allow for simple gen.
Probably 3 floors.
Stairs between floors.
Made of Limestone (because it's a white wight tower :P).
Maybe some dungeon specific trap block (ideas?)
Perhaps a better loot item as the prize for beating the dungeon?
Fancy spawner block will be used because Oli wants that ;)

**Comment by MrCompost** [comment]
*Squee* Sounds about right, some trap blocks sound neat too. I'll have a talk 'bout them.

**Comment by vadis365** [comment]
This will be totally reworked due to disagreements on creative control.
All structures and models for this are now under the Iron Fist of Triple.
Please open a new issue for this when it is ready to be implemented.

**Comment by MrCompost** [comment]
For christs sake Len

**Comment by MrCompost** [comment]
Ok... *slowly opens lid again*

**Comment by vadis365** [comment]
Closing because it's in and just needs some tweaks as per the new issue I made.

**Comment by MrCompost** [comment]
=D
