### ISSUE TITLE
Underground pitstone structures

### ISSUE THREAD

**Issue by vadis365** [Angry-Pixel/The-Betweenlands#219]
I don't know what these are - Please post details here.

**Comment by MrCompost** [comment]
Basically just simple underground ruins with small dungeons not too unlike the stuff on the surface atm.

**Comment by imdutch21** [comment]
can be seen as done now? Only thing I can think of is more structures, but then I need more sturctures to add.

**Comment by MrCompost** [comment]
Were there not more in the world I sent?

**Comment by imdutch21** [comment]
oh yea, I see I missed some. Probably just over looked them or something

**Comment by TheCyberBrick** [comment]
Is this done?

**Comment by imdutch21** [comment]
I'd consider it done

**Comment by MrCompost** [comment]
I'm not happy with my builds, but for the sake of a release yes. At some point I'd like them revisited though.

**Comment by TripleHeadedSheep** [comment]
Im closing this for now as the current ones will do for the release.
