### ISSUE TITLE
Finish any remaining herblore stuff, including the guide

### ISSUE THREAD

**Issue by vadis365** [Angry-Pixel/The-Betweenlands#221]
Title says what is needed - ask Oli for specifics.

**Comment by MrCompost** [comment]
Me? I have no idea =P
It looks very much done to me, but I need Sam to check.

**Comment by TheCyberBrick** [comment]
What's there to finish? The mechanics are all implemented afaik? Maybe only the book needs to be tweaked, but that's @imdutch21 's job

**Comment by MrCompost** [comment]
I was hoping you'd know =P
Any potions left to do?

**Comment by TheCyberBrick** [comment]
Yes, the 3 special ones, but we decided to add those after release because they're a lot of work. We can already add the recipe items though for some extra loot and so you dont have to generate new chunks for it after the first release.

**Comment by imdutch21** [comment]
For the HL Book I'm waiting for Len,  but I think that is mostly finished to

**Comment by TripleHeadedSheep** [comment]
This is done, right? Closing it, if not, feel free to re-open
