### ISSUE TITLE
Dreadful Peatmummy (new mini-boss)

### ISSUE THREAD

**Issue by vadis365** [Angry-Pixel/The-Betweenlands#226]
New mini-boss mob.
The model is is and some basic things thanks to Josh.
Please add AI and behaviors to this issue for clarification.

**Comment by BobMowzie** [comment]
I'm going to list the attacks and abilities I have in mind.
1. Basic collision damage
2. Summoning peat mummies
3. Tentacle sweep (arc aoe damage)

**Comment by MrCompost** [comment]
They sound perfect, the only other thing to consider would be spawning. Me and Len both thought it'd be good to have a craft able item that, if thrown down on a large enough ground area within a sludge plains or marsh biome, 'summons' the peat mummy.

**Comment by BobMowzie** [comment]
That sounds good, but I've never done something like that. I'll worry about that when everything else is done.

**Comment by MrCompost** [comment]
No problem, I'm sure someone knows how.

**Comment by TheCyberBrick** [comment]
Oh god, summoning Peat Mummies? Are you the devil? :p

**Comment by MrCompost** [comment]
Ok so... this needs (and I mean needs!)

Spawing
Drops if not done already
Boss music if that's simple enough
The scream when summoning Peat Mummies
Then we're all good :)
