### ISSUE TITLE
Giant Toad (new tameable/mountable mob)

### ISSUE THREAD

**Issue by vadis365** [Angry-Pixel/The-Betweenlands#229]
This one should be fairly easy - the model and mob are in game - it just has nothing coded to make it tamable and a mount. Please explain mechanics below.

**Comment by MrCompost** [comment]
Ok, lets keep this simple so it can be done quickly.
Health points - 30
Spawn - Swamplands, Patchy Islands (rare)
Drops - none (was thinking of changing the frog's legs to toad's legs and using them, but I'd much rather have two separate mobs. Also who the hell eats toad's legs?)
I figured that their AI/taming could work just like ocelots, only with dragonfly wings. They can then be mounted and ridden on, no saddle required. The can be healed using dragonfly wings.

**Comment by MrCompost** [comment]
Model done. Texture could do with a redo.
