### ISSUE TITLE
Loading screens 

### ISSUE THREAD

**Issue by vadis365** [Angry-Pixel/The-Betweenlands#231]
If anyone knows someone who can do these then please grab em, because otherwise Oli will do them and they'll suck :P

**Comment by Sevenoon** [comment]
Uh, what kind of loading screens do you mean? Are you talking about ones like [these?](http://media-minecraftforum.cursecdn.com/attachments/167/728/635853807127759025.jpg)

**Comment by MrCompost** [comment]
Yup, but the background will be replaced with different pieces of mock concept art or something of the sort.

**Comment by Sevenoon** [comment]
But what kind of help is needed? As in coding them in, or designing them?

**Comment by MrCompost** [comment]
Both.

**Comment by MrCompost** [comment]
Any news on this?

**Comment by jredfox** [comment]
if you do make a custom loading screen please make an option in the config to disable it and all of it's code to not be loaded when the boolean is false.

**Comment by TheCyberBrick** [comment]
Yeah, it already does have a config entry for that
