### ISSUE TITLE
Wight rework

### ISSUE THREAD

**Issue by TheCyberBrick** [Angry-Pixel/The-Betweenlands#232]
Wight needs a rework like the Tar Beast. Its AI sucks at the moment and it's not really a threat at all.
I already have some ideas for it, I'll work on this when I have time.

**Comment by MrCompost** [comment]
Tbh this isn't totally necessary but changes would be welcome. I have *some* ideas, but I'd rather they were used on a separate mob tbh. So yeah, I got nothing for now. I'll let you know if I do.

**Comment by TheCyberBrick** [comment]
The wights really do suck as it is now and it's a pretty iconic mob of this mod which is why I'd say it should be at least half decent. It also gets stuck all the time :P

**Comment by MrCompost** [comment]
Yeah. Dave was gonna give them to ability of walking on water actually but never got around to it. That'd stop them getting stuck in the marsh.

**Comment by TheCyberBrick** [comment]
I think this is done
