### ISSUE TITLE
Shader mod compatibility

### ISSUE THREAD

**Issue by TheCyberBrick** [Angry-Pixel/The-Betweenlands#233]
**Low priority**, just putting this here so I don't forget.

Depending on the shader pack we see issues like water having no texture (just a solid light blue), the bottom half of the screen being completely grayed out, and no shadows.

Here are the versions of applicable mods we're using (so you can reproduce what we're seeing)
TheBetweenlands-1.7.10-1.0.0-alpha.1-build.132-universal
OptiFine_1.7.10_HD_U_C1 (recommended version for ShadersModCore)
ShadersModCore-v2.3.31-mc1.7.10-f (recommended build for 1.7.10)
Forge version 10.13.4.1566
Shaderpacks that i've tried, with issues
Sildurs Vibrant Shaders v1.13 High (bottom half of screen is gray when looking forward, and everything is gray when looking down, no shadows)
Sildurs Vibrant Shaders v1.07 High (beta) (no shadows, water has a flat blue texture, not transparent)
any of the SEUS shaders (no shadows)
Without this mod installed, all shader packs work without any issues

**Comment by williamhcarlton** [comment]
The CyberBrick I don't understand the context of this entry. I am seeking out solutions to the issue of having gray fog at the bottom of the screen when using a certain shaderpack. It's Sildur's shaderpack. I'm running optifine on 1.6.4 version of Minecraft for Attack of the B Team modpack. Everything runs beautifully in singleplayer, but as soon as i join a server everything below eye level roughly shows up as gray fog. I wonder if you might have any insight about this.

**Comment by TheCyberBrick** [comment]
Uhm, I don't quite understand what you mean.
This was a bug report from somebody and I put it here so we can have a look later on.
Also, why are you talking about MC 1.6.4 when this mod is only for 1.7.10?

**Comment by TheCyberBrick** [comment]
This should now be fixed by 75724fbbe45f4167eb2a364255d2848ce3da5fed

I also noticed that the Shaders Mod seems to cause a black screen when you start the game and enter any dimension that is not the overworld (e.g. the Nether), even without the Betweenlands installed.
