### ISSUE TITLE
Item equpping/unequipping

### ISSUE THREAD

**Issue by TheCyberBrick** [Angry-Pixel/The-Betweenlands#234]
The amulet currently only uses a keybind to unequip and item right click to equip. To make this more extensible in the future, for example for volar pad glider equipping, I'll add a radial menu when holding a keybind to equip and unequip certain items from the inventory. Like that you can quickly swap equipped items and it's fairly intuitive.

**Comment by MrCompost** [comment]
Your radial menus? Yay! :D

**Comment by TheCyberBrick** [comment]
Yes, that one. I'll probably change it up a bit so it fits better

**Comment by TheCyberBrick** [comment]
This is done. I might still chabge the design a bit
