### ISSUE TITLE
Half Tree

### ISSUE THREAD

**Issue by TripleHeadedSheep** [Angry-Pixel/The-Betweenlands#236]
They have returned:
![2016-02-25_17 12 46](https://cloud.githubusercontent.com/assets/5305563/13325764/7ef0feea-dbe3-11e5-985b-188f6a24fcfe.png)
Although this is the first one I ever encountered on my end...

**Comment by MrCompost** [comment]
I've always had them.

**Comment by vadis365** [comment]
Chunk gen error.
Was this done whilst flying around or through natural movement (walking around)?

**Comment by TripleHeadedSheep** [comment]
I agree with chunk derping due to lag.
I was flying around (not at a high speed though) and had quite some lag since Optifine doesnt work with the BL for me ;)

**Comment by TheCyberBrick** [comment]
We can't identify the issue for now, maybe we can look at it after the release
