### ISSUE TITLE
Shockwave sword

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#237]
Name ideas needed guys!
In most ways like a diamond sword, but when swung it also releases a shockwave. The closer the mob is to the player, the more damage the shockwave does. It could have a neat little sound to go with it to and some cool visual effect. Perhaps shaders could be employed or a particle effect. It also has a custom model (ooooo!)

**Comment by Sevenoon** [comment]
Name Ideas:
Bog Breaker
Water Waver
Swamp Awakener
Sword of a Thousand Cries (Name has correlation with the lore)

**Comment by iLexiconn** [comment]
Why not just shockwave sword?

**Comment by Sevenoon** [comment]
^ Or that too...

**Comment by TheCyberBrick** [comment]
Any suggestions on how the sword works?

**Comment by MrCompost** [comment]
Basically just everything I said in my initial comment. Anything other details needed?

**Comment by TheCyberBrick** [comment]
Well, I'm not exactly sure how that shockwave should look

**Comment by MrCompost** [comment]
http://static.tvtropes.org/pmwiki/pub/images/180px-SwordBeam.jpg =P
