### ISSUE TITLE
Structures gen in clusters

### ISSUE THREAD

**Issue by TripleHeadedSheep** [Angry-Pixel/The-Betweenlands#241]
Right now we have the ruïn parts in the marshes and the pitstone structures scattered all over the place.
If we could let them gen in clusters, it would clean the landscape a bit and then we can assign world areas to them.
Not sure how do-able this is.

**Comment by TheCyberBrick** [comment]
That's quite simple

**Comment by TripleHeadedSheep** [comment]
Who should I assign to this?
It also requires for them to add a few more structures that Bart didn't get in yet.
