### ISSUE TITLE
The food sickness thing doesn't seem to work properly.

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#243]
I ate some Wight Hearts (presumably this issue applies with any food though), when I got two of the 'half sick' messages at once. The next time I tried to eat one it went straight to completely sick.

**Comment by TheCyberBrick** [comment]
Got no feedback, I'll assume that this is now working properly

**Comment by MrCompost** [comment]
It seems to work fine from the little testing I did with it. I can do more if you want.
