### ISSUE TITLE
Remove Chock-A-Block animation

### ISSUE THREAD

**Issue by TheCyberBrick** [Angry-Pixel/The-Betweenlands#244]
We have to keep the block in the mod but remove the animation

**Comment by MrCompost** [comment]
Aw, why? It was easily the best thing in the mod! D=
File too big?

**Comment by TheCyberBrick** [comment]
Yeah, it makes the generated texture atlas way too huge.
I might be able to make it render as a TE though so that it doesn't have to be loaded into the atlas.

**Comment by MrCompost** [comment]
can't we just shrink it? :P
