### ISSUE TITLE
Fortress bricks explosion resistant

### ISSUE THREAD

**Issue by TheCyberBrick** [Angry-Pixel/The-Betweenlands#245]
The bricks used in the fortress should be explosion resistant so you can't just blow your way through

**Comment by MrCompost** [comment]
Eh... doesn't seem worth the extra effort to do that. Some people will cheat anyway one way or another. I seriously wouldn't worry about it.

**Comment by TheCyberBrick** [comment]
It's just one line though

**Comment by MrCompost** [comment]
oh can it be applied using the area selection thing you did?

**Comment by TheCyberBrick** [comment]
No

**Comment by MrCompost** [comment]
How descriptive. Well, whatever. If you say so.
