### ISSUE TITLE
Stuff to finish up for Vadis (a reminder)

### ISSUE THREAD

**Issue by vadis365** [Angry-Pixel/The-Betweenlands#247]
Item Blocks for:
- [x] Possessed Block (if needed).
- [x] Spike Traps.
- [x] Item cages (add new model).

Blocks:
- [x] Add or remove correct drops for the above blocks.
- [x] Make fortress blocks blast resistant.

Mobs:
- [x] Chiromaw - drops (wing item that resets food apathy).
- [x] Pyrad - remove or reduce smoke and fire particles, add drops, recode flying AI.

Fortress:
- [x] Add Secret rooms (maybe 2 maybe more).
- [x] Add structure to decorator.
- [x] Add random mushroom blocks here and there on in the basement for prettiness.
- [x] Add proper air check to avoid slicing the world up

~~Run a bit of code for random thorns and vines and whatever.~~  depricated
will add to list when I remember more :P

**Comment by TripleHeadedSheep** [comment]
Will the Pyrads get a little bit of animation added to them?

**Comment by MrCompost** [comment]
Only one thing? Yeaaaaaahh!! =D
