### ISSUE TITLE
Some last few things I came across that need adjustment or fixing

### ISSUE THREAD

**Issue by TripleHeadedSheep** [Angry-Pixel/The-Betweenlands#250]
~~- The world seems a lot darker now that the skylight has been removed. I can barely see anything with my brightness fully up.~~

~~- The world seems more barren. I've come across several empty islands and marshes.~~

~~- The Cragrock Tower needs a world area added to it (with auroras active)~~

- I'm not sure if they're added to the gen, but the recent structures Bart was working on are nowhere to be found. These should be the mudbrick structures and iirc some more of the structures set with the arches.

~~- The BL items still corrode in the Overworld.~~

~~- The Hag Slayer, Critter Cruncher and Sludge Lance are under a Vanilla tab in creative.~~

~~- The clusters of structures could do with world locations, but I'm not sure if we can get this done.~~

~~- The Primordial Malevolence drops the loot items before his death animation.~~

NEW:
The world location 'Wilderness' should be changed to 'Caves', 'The Underground' or 'Caverns' for the caves

**Comment by MrCompost** [comment]
5, 6 and 8 don't really need addressing imo. The rest, sure.

**Comment by TripleHeadedSheep** [comment]
But 6 would be something very easy to do.
And regarding 8. I killed the Primordial Malevolence when he was flying just above the edge. The ring fell all the way down :/

**Comment by MrCompost** [comment]
The mud stuff has been added, but only two were done and it looks likely that the rest wont be done before release.
