### ISSUE TITLE
Change Either Bed recipe or Sickle

### ISSUE THREAD

**Issue by vadis365** [Angry-Pixel/The-Betweenlands#255]
Requiring Valonite to harvest moss for a bed breaks the progression balance.
Setting a bed as a spawn point should be quite early game mechanics.

**Comment by TheCyberBrick** [comment]
I'd add a second recipe that also works with the blocks, then it only requires 2 syrmorite and the moss blocks which can be found almost everywhere.

**Comment by vadis365** [comment]
we have what Sam said - so closing
