### ISSUE TITLE
Food apathy needs tweaking

### ISSUE THREAD

**Issue by vadis365** [Angry-Pixel/The-Betweenlands#262]
Not sure if this is actually working properly.
I'm eating mushrooms and getting a hunger effect - but they still say 'tastes good'
Maybe the amounts need lowering or something or the hunger effect removed until the tool tip is supposed to change.

**Comment by TheCyberBrick** [comment]
You realize that the mushrooms always give the hunger effect, right? x)

**Comment by TheCyberBrick** [comment]
Oops accidentally closed it

**Comment by TheCyberBrick** [comment]
You start to get sick of a food after eating it 48 times. We might have to lower that a bit, but not too much. The player already has enough to micromanage (food, decay, corrosion **and** food apathy)

**Comment by TheCyberBrick** [comment]
Btw, the food apathy doesn't give you hunger. It just lowers the food/decay you get from eating that food. The only exception is the Chiromaw Wing which does give you hunger when you're sick of it
