### ISSUE TITLE
Mob Balancing

### ISSUE THREAD

**Issue by TripleHeadedSheep** [Angry-Pixel/The-Betweenlands#263]
Silt Crabs - take three fucking valonite hits, they should be two hits with octine imo.

Tar Beasts - one or two are fine when you have full valonite... but a dungeon is way too hard. Im not sure what health/damage would be best for them, they should be strong, yes, but the dungeon is just too OP.

Wights - we all know that, they're too common and too powerful or something (I havent encoutnered much Wights yet, so I wouldn't know exactly)

Chiromaws - too common on the surface, apparently the spawn code needs to be rewritten for this? So, maybe save this for 1.9

Geckos - also take three or two valonite hits. They should also take two octine hits, or maybe even one...

Feel free to add more mobs to the list

**Comment by WightofShadows** [comment]
More specifically what should be addressed for the Wights, most from Sam:
-Decrease their view range to make the sneaking tactic more useful (at the moment they can target with possession from completely off screen, waaay too far)
-Make them not use the possession attack until they hit you at least once
-Make their magic damage less (I would half it at least)
-Make them only deal magic damage in possession form (not sure if this is already the case)
-Make the volatile souls disappear upon the Wight's death

**Comment by TheCyberBrick** [comment]
"Silt Crabs - take three fucking valonite hits, they should be two hits with octine imo."
Yup, that's too much x)

"Tar Beasts - one or two are fine when you have full valonite... but a dungeon is way too hard. Im not sure what health/damage would be best for them, they should be strong, yes, but the dungeon is just too OP."
Decreasing the spawn rate and setting the max entities to 1 should fix this

"Wights - we all know that, they're too common and too powerful or something (I havent encoutnered much Wights yet, so I wouldn't know exactly)"
Working on this

"Chiromaws - too common on the surface, apparently the spawn code needs to be rewritten for this? So, maybe save this for 1.9"
We're using a custom spawning system, no need to rewrite anything :P

**Comment by MrCompost** [comment]
"We're using a custom spawning system, no need to rewrite anything :P"
Ah, that's good :)
