### ISSUE TITLE
Structure spawn rate

### ISSUE THREAD

**Issue by lilmoefow** [Angry-Pixel/The-Betweenlands#268]
Hey, good news is that the structure required to access the between lands spawns in modded swamp biomes..  the bad new is they spawn in almost every chunk.  

http://imgur.com/Ygt8pql

http://imgur.com/cAfjlSZ

there is about 15 of them in a 200 block radius. i don't think that is intended? 

Forge 1614
TheBetweenlands-1.0.1-alpha-universal
extrabiomesxl_1.7.10-3.16.4

**Comment by TheCyberBrick** [comment]
That because this is not a vanilla swamp. There are way more trees in the vanilla biome which causes it to generate less often. You can change the frequency in the Betweenlands config.

**Comment by lilmoefow** [comment]
I said in my  comment that its a modded swamp.  And when i was looking through the configs last night i skipped by that config option cause its hidden between all the biome id configs. Sorry for the inconvenience.  Do you think a spawn rate of 1 suffice? or should i just keep testing/playing with it to find the right value?
