### ISSUE TITLE
Herblore is broken?

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#269]
A few people have reported that they can't figure out  how to make any Elixirs, and having just tried to make an Elixir of Strength I also can't get it to work. It just keeps returning the aspects to me in separate vials. Need feedback on this really.

**Comment by TheCyberBrick** [comment]
Uhm did you use the exact aspects?

**Comment by MrCompost** [comment]
Yup, tried it three times. Azuwynn and Ordaniis.

**Comment by TheCyberBrick** [comment]
Works fine for me.
Did you brew it for right amount of time?

**Comment by MrCompost** [comment]
Er yeah, I think so. Changed colour and all.

**Comment by TheCyberBrick** [comment]
Was the infusion red?

**Comment by MrCompost** [comment]
Er no. First time it was purple, second and third time it was light blue.

**Comment by MrCompost** [comment]
The same thing is happening for those French guys who are trying to make a video/article of the mod. They said they couldn't get it to work.

**Comment by TheCyberBrick** [comment]
What ingredients did you use?

**Comment by TheCyberBrick** [comment]
Just to make sure: Purple is the color of an invalid infusion, light blue (or later dark blue) is just the gradient of the infusion, once it's done it should be red and then you know it's ready

**Comment by MrCompost** [comment]
Oh, so it turns blue then red...?

**Comment by MrCompost** [comment]
And I used Azuwynn and Ordaniis..

**Comment by TheCyberBrick** [comment]
Invalid infusion: http://puu.sh/o9BAK.png
Infusion in progress: http://puu.sh/o9BA1.jpg
Finished infusion: http://puu.sh/o9BuV.jpg

**Comment by MrCompost** [comment]
Ah. How er... intuitive :P
I forgot about that, when I checked the wiki it just said "turns a certain colour."

**Comment by TheCyberBrick** [comment]
Why is that unintuitive? I added that because how else could you tell that the infusion is done completely? :P

**Comment by MrCompost** [comment]
It's alright, I was joking. There's just nothing ingame that actually tells you that. I fixed the wiki.
Btw I was wondering, wasnt the text just going to be debug? I dont see why its necessary tbh

**Comment by TheCyberBrick** [comment]
It **is** only debug x)
If you want we can add a sound when the infusion is done, should make it a bit more obvious

**Comment by MrCompost** [comment]
Oh, oops lol
I actually think it'd be best to get rid of the in progress colour, so numb-nuts like me don't mistake it for being finished.

**Comment by TheCyberBrick** [comment]
Nah, I don't want to remove that. If we add a sound or some particles it should be fine really, especially since the finished color is the same as the color of the liquid inside the elixir vial. We just have to update the wiki and add a tutorial to the Guide Book once that's finished (or Herblore book).

**Comment by imdutch21** [comment]
I'd say just add a third tab to the HL book as the guidebook isn't going to be in for a while

**Comment by MrCompost** [comment]
Yeah, I agree with both actually. I'll commit a sound. Sorry I can't be around properly, I'm all over the place atm.

**Comment by TheCyberBrick** [comment]
Dave is going to rage about the spam soon

**Comment by MrCompost** [comment]
Spam? What spam?

**Comment by TheCyberBrick** [comment]
Dude, why would I don't know?

**Comment by vadis365** [comment]
ahem...

**Comment by MrCompost** [comment]
Yes?
