### ISSUE TITLE
User ShadowJohnX's findings

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#270]
Taken from a reply to from the forum thread.

1. ~~If using a life crystal that is 1-9% drained then used in the animator for a item scroll, it goes pass to the negative and lost it textures.~~
2. ~~Mire Snails don't lay eggs when breed.~~
3. ~~Silt Crab Claw textures should be more red. Looks like it been cooked rather then it being raw.~~
4. ~~Craftable Weedwood Logs, (For building reasons). - (FIXED, RIGHT?)~~
5. ~~Animator breaks with one punch and does not give back the item.~~ now has harness rest is right
6. ~~Duel Furnace does not work right with Hoppers, (pulls sulfur out of fuel slot).~~ It's time to DU-DU-DUEL!...furnace
7. Using the Shockwave Sword's ability's breaks blocks during the Wight Tower Boss Fight
8. ~~Trying to use Wight Hearts to refill life crystals does not work.~~

**Comment by WightofShadows** [comment]
#2 and 9 are fixed in the next patch. I think by #4 he means you should be able to craft the logs, not use them in crafting (that is for sure fixed in 1.0.1, I checked).

**Comment by MrCompost** [comment]
He also reported these. 

1.Getting stuck on side pillars.
2. Item Cage should be able to be mined from all sides after being mined once.
3. Item Cage should be allow to store any items, or make it a cooler version of the Gecko Cages 😉

I don't think the item cage should be dropped at all though tbh.

**Comment by WightofShadows** [comment]
Hmm...not sure about 2, the puzzle should require total completion around the room and if you have to break one from directly underneath anyways it doesn't help with figuring out what to do. For 3, there could be a version of the item cage you craft that doesn't act like the ones in the fortress.
