### ISSUE TITLE
Unconfigurable Potion ID Issue

### ISSUE THREAD

**Issue by whitestarx0312** [Angry-Pixel/The-Betweenlands#272]
I went into the Wight fortress and had this crash:
http://pastebin.com/Z0nZ2333

Betweenlands: TheBetweenlands-1.0.2-alpha-universal

I think this is a potion ID issue and I would fix it without bothering you guys but I couldn't find a config for it and I'm unsure which mod is using that potion ID.

**Comment by TheCyberBrick** [comment]
I'm not sure if it's a potion ID conflict or if it just ran out of free IDs. In 1.7 there's a limit of 128 potions and the Betweenlands alone adds 30 or so potion effects.
We'll probably implement our own system so we don't have to use the standard potion effects for our elixirs, but until that's done we'll make the potion IDs configurable in the next update.

**Comment by imdutch21** [comment]
We might not need to, I think that limit is gone/bigger in 1.9

**Comment by TheCyberBrick** [comment]
Yes, but it'll take a while until the mod is fully updated

**Comment by imdutch21** [comment]
Can't you extendo the potion list? I'm sure I used to do that in my other mods

**Comment by TheCyberBrick** [comment]
Made configurable in 8fa1ce2fbffa7d037c9b9138aa1cde59716e1212
