### ISSUE TITLE
This mod needs to calm the fog down

### ISSUE THREAD

**Issue by purpleposeidon** [Angry-Pixel/The-Betweenlands#278]
Can't see 5 meters ahead:
![](http://i.imgur.com/67KWOCV.png)

Either I can't see my own hand, or I can't see myself in 3rd person
![](http://i.imgur.com/FNMPDl9.png)

**Comment by TheCyberBrick** [comment]
Hmm, the cave fog is intentional but I guess we could add a lower limit so it doesn't get too extreme.

**Comment by vadis365** [comment]
maybe we could add an option to 'shut the fog up' ;)

**Comment by MrCompost** [comment]
Hmm... yeah it is pretty extreme. Though I quite like Dave's suggestion :P
