### ISSUE TITLE
Shaders bug

### ISSUE THREAD

**Issue by purpleposeidon** [Angry-Pixel/The-Betweenlands#279]
My driver reports that GL_ is a reserved macro prefix.

**Comment by TheCyberBrick** [comment]
I need more information on this. What GPU and drivers? Stack trace? OpenGL error? Any other mods installed (e.g. Optifine)? Do the vanilla 1.7.10 shaders work properly (aka the "Super secret settings")? And any other information that could be related to this would be useful.

**Comment by purpleposeidon** [comment]
I don't have the error handy, but specifically:
assets/thebetweenlands/shaders/mc/program/blshader.fsh

#define GL_EXP 2048
#define GL_LINEAR 9729

should be renamed to something like BL_EXP and BL_LINEAR.

**Comment by TheCyberBrick** [comment]
Ah I see, makes sense. Thanks
