### ISSUE TITLE
Crash on loading in heavily modded environment

### ISSUE THREAD

**Issue by DrTeath** [Angry-Pixel/The-Betweenlands#288]
I added version 1.0.2 to my personal mod pack and I am getting a rather weird  'java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer' crash. 

The crash occurs while loading in to minecraft, my pack is generally well behaved, and I have not seen a crash like this before.

I cleared my logs files/folders then re-launched the pack to create clean logs, in the hope that it helps you resolve the issue.
Mod list should be in the log files.

[crash-2016-04-15_21.41.18-client.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/221219/crash-2016-04-15_21.41.18-client.txt)
[fml-client-latest.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/221221/fml-client-latest.txt)
[fml-junk-earlystartup.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/221222/fml-junk-earlystartup.txt)
[latest.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/221223/latest.txt)

**Comment by pau101** [comment]
For a quick solution, add a "Z" to the beginning to the Fairy Lights jar name.
`fairylights-1.4.0-1.7.10.jar` →`Zfairylights-1.4.0-1.7.10.jar`
This makes Fairy Lights load after The Betweenlands
