### ISSUE TITLE
changes in code are not seen ingame.

### ISSUE THREAD

**Issue by RCXcrafter** [Angry-Pixel/The-Betweenlands#289]
I wanted to add a few more items to the ore dictionary, so I forked this mod, cloned it and installed forge like in this tutorial: http://www.minecraftforge.net/wiki/Installation/Source
Then I tried to run the client to see if everything worked properly. At first it didn't work but thanks to the amazing tutorial I was able to get it working. I then made some changes to the code and launched up the client and I noticed that none of the changes I made could be seen in the game.

What do I need to do to get this working?

**Comment by TheCyberBrick** [comment]
I don't see how this is specific to our mod.  You should ask someone on the minecraft forge forum instead.

**Comment by RCXcrafter** [comment]
I've done the same thing with other mods before using the exact same steps and everything worked fine, can you tell me what steps you followed?

**Comment by TheCyberBrick** [comment]
Fork the repo, run the gradle commands and that should be all. It's working for me and the other team members as well. Are you running it from an IDE?

**Comment by RCXcrafter** [comment]
Yes, I'm using eclipse.

**Comment by TheCyberBrick** [comment]
That's weird, what are you trying to change?

**Comment by RCXcrafter** [comment]
I'm trying to add some items to the ore dictionary and making some recipes use the ore dictionary.

I tried installing everything from scratch and for some reason everything works now. I didn't take any different steps so I have no idea what caused this.

**Comment by vadis365** [comment]
Sorry - late to this.
Wouldn't just running MineTweaker with the mod in MC proper achieve what you want without the need to create an unofficial version of the mod that we can't support or debug errors from?

**Comment by RCXcrafter** [comment]
Well, I do have minetweaker but I thought this should be in the mod by default. So I was going to make a pull request. In fact, I'm doing that right now.

Am I not supposed to do that?
