### ISSUE TITLE
Shader render at mobs

### ISSUE THREAD

**Issue by DiceNyan** [Angry-Pixel/The-Betweenlands#290]
Hi there! Shaders dont works at standart mc world. How about to resovle it?

**Comment by WightofShadows** [comment]
They're made to not work in the Overworld, otherwise it would cost performance. Besides, you're really only supposed to see them in the dimension.

**Comment by DiceNyan** [comment]
Okay. How i can made to shader works in Overworld? I think about make Overworld addon.

**Comment by DiceNyan** [comment]
I made this. Thanks for very good mod. Issue can be closed.
