### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by DiceNyan** [Angry-Pixel/The-Betweenlands#291]
Hi again. Im sorry, but can you guys help me with making another shader? I have one fsh and vsh ready code, but i cant apply it in mc. I think it need json with some parameters. How i can make that thing works?

**Comment by TheCyberBrick** [comment]
This does not belong here, the issues are for bug reporting and/or suggestions.
Look at how our shaders are done, all the source is available. If you still have questions you can ask somewhere esle, but please not here.
