### ISSUE TITLE
Optifine Issue

### ISSUE THREAD

**Issue by 63502** [Angry-Pixel/The-Betweenlands#298]
I have a serious rendering error with this mod when I have optifine installed in my minecraft instance. Whenever I enter a portal to betweenlands in the portal tree, my screen goes absolutely black, with nothing, not even the hotbar/gui/ esc. screen rendering after I do so. It also appears that when this error occurs, the game either just continuously runs the sound of traveling through the portal without actually sending me to the dimension, or it sends me to the dimension, but it does not load or render anything when I get there, so I end up stuck with a black screen with betweenlands background sounds until I exit the game and reload. If I am in the dark screen while stuck in dimension state when I re-enter the world, the game will just continue with that error untill I close the game again. 

I have confirmed that this is a problem with optifine, and if I uninstall optifine, the dimension will load  just fine, although my game becomes too laggy to play properly.

Is there any way to fix this?

If not, do you know of any other mods like optifine that are compatible with the betweenlands mod?
(I have 163 mods currently, and without fastcraft+optifine, I can't play my mod set at all due to lag)
(fastcraft has no effect on the optifine error)

Forge Version:
1.7.10 - 10.13.4.1614

Current Optifine version:
Optifine_1.7.10_HD_U_D4

Current Betweenlands Version
1.0.3-alpha

**Comment by TheCyberBrick** [comment]
Set "Fast Render" to OFF

**Comment by 63502** [comment]
Ok, thanks. I'll try it out.

**Comment by TheCyberBrick** [comment]
@63502 Is it working now?

**Comment by 63502** [comment]
It seems to be good at the moment.

**Comment by TheCyberBrick** [comment]
Cool, I'll close this then

**Comment by ILOVEMODS** [comment]
Hey, I have a problem. Whenever I try using optifine with betweenlands on 1.7.10 it crahses. Can you help me?

**Comment by godemperoroftheworld** [comment]
Don't hijack other issues. Open your own.
Optifine breaks a lot of mods
Have you tried running with just the betweenlands? With just optifine?

**Comment by ZonkoTheGreat** [comment]
I uninstalled Betweenlands, but when I launch or create a new world, it crashes and says there's an issue with the Betweenlands client.  But I deleted the mod so why is it still appearing?

**Comment by pau101** [comment]
@ZonkoTheGreat You need to remove The Betweenlands core jar that is also in the mod folder (it gets automatically extracted at runtime). But also, as @daPoseidonGuy just said before you:
> Don't hijack other issues. Open your own.
