### ISSUE TITLE
Any have Swamp Grass spawning in the overworld?

### ISSUE THREAD

**Issue by thediggyman** [Angry-Pixel/The-Betweenlands#300]
I'm thediggyman from the adventurepros channel... Is it a thing to have swamp spawn in the overworld or is it on my side the problem

**Comment by Flameminer221** [comment]
That's a problem.

Check to make sure you don't have a biome ID conflict. This will usually happen in the Overworld if you have something like Biomes O' Plenty installed, and will make biomes from other places generate in the Overworld (which they are not supposed to do).

If you don't want to check each config, use this mod. It crashes the game if there is a biome ID conflict and tells you which ones are conflicting with each other, and which ones are available.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2387300-say-no-to-id-conflicts-install-anti-id-conflict

**Comment by TheCyberBrick** [comment]
Yes, that's caused by a biome ID conflict

**Comment by thediggyman** [comment]
Thanks guys... we will be helping get the word on your mod soon...

**Comment by Flameminer221** [comment]
So just change the IDs, it should work fine after that.
