### ISSUE TITLE
Should food sickness be buffed?

### ISSUE THREAD

**Issue by Flameminer221** [Angry-Pixel/The-Betweenlands#301]
Food sickness is barely a problem right now, especially since you can just switch between nettle soup and reed donuts (with occasional mushrooms, sap balls, etc.) without a problem, keeping "Tastes good" on the tooltip. And then there are the mobs that spawn and drop meat too, which can be eaten to help keep food sickness at bay. So far I have yet to see a single "Tastes plain".

Should it be made so that food sickness increases quicker, so the player has to alternate more often? Not too quick, maybe something like 15 times eaten before becoming "plain" as opposed to 22, the current one. Give more need for alternating food and chiromaw wings, I guess.

**Comment by MrCompost** [comment]
Yeah, I agree with this actually. Doesn't have much an effect right now.

**Comment by TheCyberBrick** [comment]
ba0430b26c7372444490c1847f5303b1cfa2b645
