### ISSUE TITLE
(Suggestion) Mobs aren't really spawning that often

### ISSUE THREAD

**Issue by Flameminer221** [Angry-Pixel/The-Betweenlands#302]
The mobs are really sort of rare. Besides mobs from spawners, I've only seen a few Wights here and there (in my current world only one underground) some groups of swamp hags, and the occasional leech/blood snail. The ground plants have probably done more damage to me than the Betweenlands mobs, maybe there should be a slightly increased spawn rate of mobs like swamp hags and wights?

**Comment by MrCompost** [comment]
We've heard this a lot, will probably look into it.

**Comment by TheCyberBrick** [comment]
Are you using any other mods and are you playing SP or MP (if so how many players online at once)?

**Comment by Flameminer221** [comment]
I'm using other mods but nothing from there spawns in the Betweenlands, and I have no CustomMobSpawner/Mob Spawn Control style mods installed. I'm playing SSP.

Yeah, I have seen quite a few of the mobs but my main reason for bringing this up was because the general lack of stronger hostiles makes the Betweenlands sort of easy, there are hostiles but they are usually just leeches or anglers.

**Comment by TheCyberBrick** [comment]
Commit ba0430b26c7372444490c1847f5303b1cfa2b645 should solve this
