### ISSUE TITLE
Is there any news about the fix-only update? :/

### ISSUE THREAD

**Issue by lightning02** [Angry-Pixel/The-Betweenlands#307]
https://github.com/Angry-Pixel/The-Betweenlands/issues/299

**Comment by vadis365** [comment]
Hello,
The bug fix update will happen when one of the team has time to release it.
1.9 updating is the priority for the team atm and 1.7.10 will eventually stop being supported.
Please don't open issues to ask questions like this - the Minecraft forums is the place for that.
This issue tracker is for reporting of bugs.
Cheers,
Me.
