### ISSUE TITLE
Dimension not loading when using together with GregTech

### ISSUE THREAD

**Issue by Kehaan** [Angry-Pixel/The-Betweenlands#308]
Using:
TheBetweenlands-1.0.3-alpha-universal
gregtech-5.09.21
industrialcraft-2-2.2.821-experimental
For minecraft 1.7.10, makes the dimension not load. When making the tree, and going in the portal the screen stays at "Downloading Terrain".

Let me know if you need any more info, to reproduce this bug.

- Kehaan

**Comment by TheCyberBrick** [comment]
Are you sure that it's not just generating the terrain? Sonetimes it takes a while until the initial area is fully generated.

**Comment by Kehaan** [comment]
I have waited up to 5 minutes, without any luck. Removing GT 5U, and it loads in under 30sec the dimension.

On a 6700k with 8gb ram allocated.

**Comment by vadis365** [comment]
So, it works without Gregtech fine?
Why is this a BL issue?

Does Gregtech have any world or oregen settings that it may be trying to do in The Betweenlands?
If so, and there is a dimension blacklist in Gregtech's config to disable generation, would it be possible to try it and see if the issue still happens?
Thanks.

**Comment by Kehaan** [comment]
I am sorry, i just reported it to both devs :)

I have just testet your idea, with blacklisting it, and it seems like that now let me enter the dimension. Thank you very much.

So if other have the issues, and use GregTech, they need to blacklist all ores in The Between Lands :)

**Comment by vadis365** [comment]
Thanks - I'm glad the issue can be sorted this easily :)
Have fun in The Betweenlands :P
