### ISSUE TITLE
Health incompatibility with TFC 

### ISSUE THREAD

**Issue by lightning02** [Angry-Pixel/The-Betweenlands#310]
I have noticed that when I add the Betweenlands with Terrafirmacraft the HP are set to 20 where they should be 1000 in Terrafirmacraft.
Could this be fixed in some way? 
Like for example an option in config file that allow to disable HP player settings from Betweenlands.

**Comment by TheCyberBrick** [comment]
Unfortunately we can't really fix that efficiently without explicitely adding compatibility for each mod that changes the player health

**Comment by lightning02** [comment]
I have to guess that this is not going to happen.. right? :/

**Comment by vadis365** [comment]
Yeah, I don't think this is a high priority thing - sorry
TFC changes a lot about the base vanilla game that we just can't cater for.
